package webapp

import javax.jws.WebMethod
import javax.jws.WebParam
import javax.jws.WebResult
import javax.jws.WebService
import javax.jws.soap.SOAPBinding
import javax.xml.bind.annotation.XmlSeeAlso


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Sdo2015PortType", targetNamespace = "http://localhost:4444/sdo2015")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso([ ObjectFactory.class ])
public interface Sdo2015PortType {

    /**
     * 
     * @param joinedNodes
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "WannaJoin")
    @WebResult(name = "joinResponse", partName = "joinResponse")
    public boolean wannaJoin(
        @WebParam(name = "joinedNodes", partName = "joinedNodes")
        ArrayOfRecords joinedNodes)

    /**
     * 
     * @param newState
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Consolidate")
    @WebResult(name = "consolidationResponse", partName = "consolidationResponse")
    public boolean consolidate(
        @WebParam(name = "newState", partName = "newState")
        ArrayOfRecords newState)

    /**
     * 
     * @param finalState
     */
    @WebMethod(operationName = "ConfirmState")
    public void confirmState(
        @WebParam(name = "finalState", partName = "finalState")
        ArrayOfRecords finalState)

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Leader")
    @WebResult(name = "leaderResponse", partName = "leaderResponse")
    public boolean leader()

}
